### ISSUE TITLE
Recommend rustup over multirust

### ISSUE THREAD

**Issue by rphmeier** [ethcore/parity#1242]
[Multirust](https://github.com/brson/multirust) is now deprecated, and the suggested replacement is [rustup](https://github.com/rust-lang-nursery/rustup.rs). The README should be updated to reflect this.

**Comment by debris** [comment]
On the other hand `rustup` is still in beta :)

**Comment by rphmeier** [comment]
Yeah, I considered mentioning that in the original issue message. Multirust was also "in beta", I suppose, if they are recommending a replacement which isn't fully complete. They just never advertised it as such. 

I think `rustup.sh` is stable, though, so we could recommend both?

**Comment by jacogr** [comment]
I had some issues lately building the master branch on Mac OS X (`git clone ; cd parity ; cargo build --release`) due to the old version of Cargo that comes with `multirust`. (as installed via `brew install multirust`). Went with `rustup` and no further issues.

Then again, my 2 wei, I'm very much a Rust newbie and sure I missed a step along the way.

**Comment by rphmeier** [comment]
Multirust should always get you the latest stable, beta, and nightly versions of Cargo/rustc with a `multirust update`. Rustup doesn't differ in this respect. I have found little practical difference between the two. Rustup's goal of toolchain management for cross-compilation extends beyond the reach of multirust, but setups where `build`==`host` will function almost exactly the same.
