### ISSUE TITLE
Chronic peer-dropping

### ISSUE THREAD

**Issue by Crypto2** [ethcore/parity#1271]
~~Hello, we've been running parity for a couple of days now switching from eth and there are 2 issues we've run into if you can help.~~

1. After a while 1-5 hours parity stops keeping up with the blockchain and falls behind either temporarily (1-2 hours) or permanently (at at least so long I can't wait anymore and have to restart it.) The server has a 3+ GHz CPU, SSDs, and this is the only thing on it so it shouldn't have any problems with I/O or anything.

~~2. eth_sendTransaction is returning a null TXID 0x00...00 for simple address to address sends (no contracts involved) instead of a correct hash or an error. It isn't sending a transaction in this case but it makes it so I have no idea what the error is. The sending code I'm using worked with ETH. It get's the gas price with eth_gasPrice(), eth_estimateGas() to calculate how much gas will be used, and then calls eth_sendTransaction. The estimated gas is only used to calculate the TX fee to deduct from the send and is not included in the eth_sendTransaction call, only from, to, gasPrice, and value are included in the parameters.~~ (Moved to #1281)

**Comment by rphmeier** [comment]
Could you post the output of `parity --version` to help us diagnose the network errors? If you are not on the latest master, please try testing it. There have been a fair few networking issues fixed since the last release, so there is a chance your issue has already been addressed.

Regarding the `eth_sendTransaction` behavior, this is actually per the standard at https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction. The zero hash indicates that the transaction is not available yet. If you are on a relatively recent version of parity, this may be related to the new trusted signer feature and @tomusdrw will be able to better diagnose it.

**Comment by gavofyork** [comment]
1. @arkpar might be able to shed light on this. please provide further details, at least the version.

2. simple sends actually make no difference. the null return means that the transaction hash is unavailable at present (but is not, yet, in an error state) or indicates/used to indicate (@tomusdrw ?) that the key is locked.

**Comment by gavofyork** [comment]
Split (2) into #1281.

**Comment by arkpar** [comment]
This is probably fixed with #1274 
@Crypto2 could you check using latest master build?

**Comment by Crypto2** [comment]
Version output is: version Parity/v1.1.0-beta/x86_64-linux-gnu/rustc1.8.0
I'm on Ubuntu 15.10/wily and used the one-line installer "bash <(curl https://get.parity.io -Lk)", unless it was updated last night or today it's the latest build from that.

**Comment by rphmeier** [comment]
@Crypto2 The 1.1 release is quite old. Try building it from source using the instructions in the README.

**Comment by Crypto2** [comment]
Ok, I'm on the latest master now.

**Comment by Crypto2** [comment]
It seems like it's getting there again but hasn't stopped yet. I had 90-100+ peers and it's slowly dropped and now hanging on at 1-2.
