### ISSUE TITLE
Remove panickers in Trie module

### ISSUE THREAD

**Issue by rphmeier** [ethcore/parity#1397]
failed DB lookups shouldn't cause panics (immediately)

related to, but does not solve #1395

**Comment by rphmeier** [comment]
I will work on landing this shortly after the in-memory trie optimization

**Comment by AlbieC** [comment]
I also think it's related to #1395 because Parity panicks and stops/exists now even without any miner connected (or trying to connect) to it. Also possibly memory related as when I close Firefox, at least Parity starts searching and then panicks and exists, as opposed to immediately if any other apps is running as well.

**Comment by rphmeier** [comment]
mostly addressed by #1776

**Comment by gavofyork** [comment]
part of #1026
