### ISSUE TITLE
Timestamp in new keys' filename

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1694]
The filename of newly created keys should include a timestamp. Consider also placing the timestamp in the metadata.

**Comment by gavofyork** [comment]
Fixed in #1700.

**Comment by A2be** [comment]
The spec is a bit fuzzy for the specifics of what you did here.
In my view, best would be to 

1. have Parity exactly match the keystore filename used in the _de facto_ standard geth (largest adoption as of early July 2016), and to
2. _also_ update the web3 spec at [https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition](url) so that _all_ implementations of Ethereum Node software might be encouraged to use a similar (or identical) keystore naming standard for their keystore files.

**Rationale** : better UX for the uncommon, but not rare, occurrence where humans are actually looking at their keystore keys manually in a file manager, and the keys of various accounts were  created by different Ethereum Node programs.  In short, better for the Ethereum ecosphere long term to make user experience easier with long-forgotten keys stored on various odd digital storage devices.
