### ISSUE TITLE
Invalid "failedCall" during trace_transaction for certain transactions

### ISSUE THREAD

**Issue by mtbitcoin** [ethcore/parity#1721]
I have noticed in certain cases when comparing the trace_transaction of GETH and debug of EthereumJ, Parity shows a "failedCall" in the trace_transaction while both the other implementations do not.

For Example if you do a trace_transaction for TxHash#0x43116a1317003e78a5747434fb5632e7a82f54951bd976163517b11cb0bb8cef  in PARITY it shows a failed call (https://gist.github.com/mtbitcoin/79d4e653e0df2f53963e55b0b722d37f)

However both GETH trace_transaction (http://etherscan.io/vmtrace?txhash=0xe68cd5463eb4c030135a99a2375a02f198bbd4c3243877930667e819ed2b316f) and EthereumJ (https://live.ether.camp/transaction/e68cd5463eb4c030135a99a2375a02f198bbd4c3243877930667e819ed2b316f) show no such errors.

**Comment by gavofyork** [comment]
are they not different transactions?

`0x43116a1317003e78a5747434fb5632e7a82f54951bd976163517b11cb0bb8cef` versus `0xe68cd5463eb4c030135a99a2375a02f198bbd4c3243877930667e819ed2b316f`?

**Comment by gavofyork** [comment]
fwiw, using the [remix debugger](http://etherscan.io/remix?txhash=0xe68cd5463eb4c030135a99a2375a02f198bbd4c3243877930667e819ed2b316f) on `0xe68cd54...`, i see that there is a single internal `CALL` at VMtracestep 141 which does indeed fail.

**Comment by gavofyork** [comment]
please also note that the other implementations probably don't even report failed internal CALLs as long as the transaction itself doesn't go OOG.

**Comment by gavofyork** [comment]
debugging the `0x43116a...` in [remix debugger on etherscan](http://etherscan.io/remix?txhash=0x43116a1317003e78a5747434fb5632e7a82f54951bd976163517b11cb0bb8cef) shows that there is indeed a failed `CALL` (at vmtracestep 909, it leaves a `0x` atop the stack). (there was another internal `CALL` earlier in the contract which didn't fail. the reason it was not included on the trace is that successful `CALL`s to built-in contracts (address=0x01-0x04) are ignored since they'd clutter up the trace database too much.)

**Comment by mtbitcoin** [comment]
@gavofyork Sorry, just to reclarify. So the failed call for "0x43116a1317003e78a5747434fb5632e7a82f54951bd976163517b11cb0bb8cef" reported by parity is actually valid, just that the other node implementations are ignoring this?

**Comment by gavofyork** [comment]
that's correct. parity is reporting failures whereas other nodes do not report them. parity is simply giving you more information.
