### ISSUE TITLE
Improve trace_transaction documentation

### ISSUE THREAD

**Issue by mtbitcoin** [ethcore/parity#1819]
I've noticed that when comparing Geth trace_transaction with Parity, Parity occasionally marks a call as a  failedCall while geth does not. An example in question is the trace for txhash 0x428f723f9ed192b6db9a144bde1e1646bf168c0f3b89ac2c677dc3d69c51985c

The 3rd call from 0x4b9e0d224dabcc96191cace2d367a8d8b75c9c81	TO 0x is marked as Failed, while Geth does not show any failedCalls. This is also particularly prevalent for other transaction failedcall's with a destination of 0x. 

This can be rather confusing if one were to do a trace_transaction across two different client implementations and receive differing failedCalls. Can these be standardized or perhaps a wiki provided to explain why these differences exist?

>> related to https://github.com/ethcore/parity/issues/1721

**Comment by gavofyork** [comment]
following the [VM trace from etherscan](http://etherscan.io/vmtrace?txhash=0x428f723f9ed192b6db9a144bde1e1646bf168c0f3b89ac2c677dc3d69c51985c), it's clear to see that there were a total of three `CALL`s, one (at [209]) which had code execute and `RETURN`ed ok, another one which succeeded (at [688]; follow the next few instructions and a `JUMP` happens, indicating a successful `1` left on the stack from the `CALL`) and the final one at [765] which failed (not clearly indicated, since `CALL`'s returned value is immediately `POP` ed, but running a VM trace confirms that the call was unsuccessful since it called builtin contract 0x000...04 with only 3 gas; it requires a minimum of 15 (see YP(204)).

**Comment by mtbitcoin** [comment]
Thanks for the additional details and explanation. I will be linking to the above explanation

**Comment by axic** [comment]
YP says base fee is 15 + 3 per 32 bytes. Seemingly Solidity had it wrong at base fee 3 + 15 per 32 bytes.

Without having looked at a traces I guess the memory to be copied was 0 bytes long.

**Comment by gavofyork** [comment]
i believe so, yes.

**Comment by gavofyork** [comment]
folding this in to #1905.
