### ISSUE TITLE
no indication of typical sync time in Wiki

### ISSUE THREAD

**Issue by nerdralph** [ethcore/parity#1861]
"Getting synced" says nothing about how long it takes to sync.  I tried out parity since it is supposed to be fast, yet after four hours it's barely over halfway synced (and seems to go slower the further it gets).

**Comment by gavofyork** [comment]
it does indeed go slower the further it gets; blocks get a steadily increasing quantity and complexity of transactions as more people are introduced to, and make full use of, the network.

it is extremely difficult to give a good estimation on how long synchronisation takes since it's heavily dependent on the hardware. e.g. on my ssd laptop, full synchronisation can take as little as 90 minutes. yet slower machines with HDDs can take even an order of magnitude longer.

the "Getting synced" page on the wiki explains how to use the snapshotting mechanism; if this is what you're trying to do then ensure you follow the instructions carefully - it should take no more than 10 minutes once you have the snapshot file downloaded.
