### ISSUE TITLE
Full JSONRPC documentation

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#1905]
Give the documentation an overhaul - sync everything (ethcore, ethcore_set, tracing, personal) up with `https://github.com/ethcore/ethereum-rpc-json` and deploy the documentation to somewhere easily accessible; link it from the wiki, README.md and FAQ.

**Comment by maciejhirsz** [comment]
This could easily become it's own issue, posting it here so it's public:

# Rust doc comments -> Markdown

## Motivation

In order to avoid maintaining multiple lists of the JSON-RPC methods available in Parity, it would 
be best to use the original Rust codebase as the _Single Source of Truth_ for documentation and the
JavaScript interface. It should be noted that having a full featured system that produces an
interface ready to be consumed by Parity.js is more challenging and would require tooling that can
operate on Rust source code as AST to understand the underlying types used.

## Types and Types

The types used in the Rust source code, while very explicit, differ from the types described in the
documentation. For example `U256` or `Bytes` can be both presented to end user as a `Data` type,
while the `BlockNumber` enum is best explained as a type union of `Quantity|Tag`. To keep the
documentation in sync with the existing wiki, the following should be an exhaustive list of allowed
types:

* `Boolean`
* `String`
* `Integer`
* `Quantity` - effectivel an unsigned integer
* `Quantity|Tag` - for block number
* `Data`
* `Hash`

## Expanding Rust doc comments

The proposal here is to use syntax inspired by Javadoc/JSDoc. Anything in the tripple-slash doc 
comment for a method will be used for the description of the method, unless the first
non-whitespace character in the line is the `@` symbol. The `@` symbol followed by a label with no
whitespace between the two constitues a _tag_. Each tag can demand a number of extra words to
follow it, usually separated by whitespace. The last word in the line can contain whitespace and
will continue to be parsed until line terminator symbol is encountered.

The following tags will be recognized by the Markdown doc generator:

| Format                                  | Purpose                                                   
|-----------------------------------------|--------------------------------------------------------
| **@param** _{Type} description_         | Listing in order the JSON-RPC parameters for the method   
| **@property** _{Type} name description_ | A number of properties can be listed _below_ a `@param {Object}`
| **@returns** _{Type} description_       | Return type with description
| **@req** _JSON_                         | Data used to construct a request example. Must contain valid JSON array of parameters. If no `@param` is present, then an empty array will be assumed.
| **@res** _JSON_                         | Data used to construct a response example. Must contain valud JSON of response data (just the value of the `"result"` field in JSON-RPC).

## Example

```rust
/// Executes a new message call immediately without creating a transaction on the block chain.
///
/// @param {Object} The transaction call object.
///   @property {Address}  from     (Optional) 20 Bytes - The address the transaction is send from.
///   @property {Address}  to       20 Bytes - 20 Bytes - The address the transaction is directed to.
///   @property {Quantity} gas      (Optional) Integer of the gas provided for the transaction execution. eth_call consumes zero gas, but this parameter may be needed by some executions.
///   @property {Quantity} gasPrice (Optional) Integer of the gasPrice used for each paid gas.
///   @property {Quantity} value    (Optional) Integer of the value sent with this transaction.
///   @property {Data}     data     (Optional) 4 byte hash of the method signature followed by encoded parameters. For details see [Ethereum Contract ABI](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI).
///
/// @param {Quantity|Tag} (Optional) Integer block number, or the string `'latest'`, `'earliest'` or `'pending'`, see the [default block parameter](#the-default-block-parameter).
///
/// @returns {Data} The return value of executed contract.
///
/// @req [{"from":"0x407d73d8a49eeb85d32cf465507dd71d507100c1","to":"0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b","value":"0x186a0"}]
/// @res "0x"
#[rpc(name = "eth_call")]
fn call(&self, CallRequest, Trailing<BlockNumber>) -> Result<Bytes, Error>;
```

The above should produce markdown in line with the
[exsiting wiki entry](https://github.com/ethcore/parity/wiki/JSONRPC-eth-module#eth_call).

**Note:** For readability the `@property` tags were indented by two spaces, but this is not
strictly necessary.

## Limits and ways to break out of them.

- There are few places were a dummy placeholder `{ ... }` is being used instead of a JSON object,
  should the details of the field not be important, or are described somewhere else (usually
  explained in a description for a property). Support for it can be added quite easily, but it
  breaks the valid JSON requirement.

- There are few places in existing documentation where a comment is being added to the example
  values. While this is theoretically also possible to add, it would also require that the JSON-ish
  structure following `@req` or `@res` be multiline, substantially increasing parsing complexity (compared to _grab everything till the end of the line, parse as JSON_).
