### ISSUE TITLE
Reduce CPU usage when idling

### ISSUE THREAD

**Issue by arkpar** [ethcore/parity#1922]
- Make sure there are no timers waking up too often
- Check ws-rs wakeups

**Comment by Zoltu** [comment]
Windows 10, 64-bit, 4 core something-or-other I am seeing regular spikes to ~40% CPU utilization that last for 5-15 seconds.  I have been unable to identify any patterns, it doesn't seem to be correlated with new blocks showing up.

**Comment by Zoltu** [comment]
After leaving Parity running in the background with no restart since one restart ~24 hours after fully syncing, the CPU usage seems to have finally stabalized without big spikes. It still has little bumps from time to time, but nothing taxing.  It is unclear if this problem was related to initial sync or *when* I started using Parity (when the geth bug took out a large chunk of the network).

**Comment by rphmeier** [comment]
Are you running in `passive` or `dark` mode?

**Comment by Zoltu** [comment]
I installed on Windows with defaults and launched it via the start menu entry, so whatever settings that uses is what I am using.

**Comment by rphmeier** [comment]
Ok, the default is `active` mode. You can run with `--mode passive` to have parity sleep and only wake periodically to resync, or with `--mode dark` to only wake on RPC interaction. Running in either one of these modes is probably ideal if you're worried about CPU spikes, although when fully synced in `active` I wouldn't expect too much CPU usage either.

**Comment by arkpar** [comment]
Fixed in #2982
