### ISSUE TITLE
Parity on local private chaine

### ISSUE THREAD

**Issue by bellaj** [ethcore/parity#2011]
Hello,

I want to run parity on a private chain. I have a previous local blockchain generated using geth i want to reuse it. May I, use geth export or is there any solution to just show parity my previous chain like --datadir for geth.
I explored parity options I found the --chain  parameter but i think it doesn't seem to allow this option. 
any suggestion?

**Comment by keorn** [comment]
Parity uses a different database format, so simply using `--datadir` will not work. You need to do `geth export FILE` and then `parity import FILE`. Since this is a private chain with custom settings, you will also need to run Parity with `--chain CHAIN-SPEC` option. [This page](https://github.com/ethcore/parity/wiki/Private-chains) shows an example CHAIN-SPEC.

**Comment by arkpar** [comment]
Please reopen if you have further questions or join the discussion at  https://gitter.im/ethcore/parity
