### ISSUE TITLE
After syncing, blocks are fetched in batches until restart.

### ISSUE THREAD

**Issue by MicahZoltu** [ethcore/parity#2199]
I downloaded and installed Parity yesterday and fully synced from nothing.  I had `geth` installed previously, though I don't believe anything other than keys were migrated from there.  Upon completion of syncing, I noticed that I was getting blocks in batches rather than as they arrived.  This continued until today when I restarted Parity for the first time after initially installing/running it and now I see blocks arriving in realtime, rather than in batches.

I suspect that on first-run it is doing some kind of fast-sync, but once it is fully synced it should automatically switch over to real-time mode.  Perhaps the problem is identifying when a sync is complete?

**Comment by arkpar** [comment]
Could you post some log output to illustrate that?

**Comment by Zoltu** [comment]
I would be happy to, though I'm not sure where to find such logs (particularly since I have restarted once and the problem went away after that first restart).  I'm on Windows 10.  I see a bunch of `.log` files in the `v5.3-sec-overlayrecent/db` folder, though I'm not sure if those are the logs you need...

**Comment by arkpar** [comment]
Just the console output if you still have it or if it happens again. Would help with investigating this

**Comment by Zoltu** [comment]
Ah, sorry, console output is onee since the restart that fixed it.  The gist was that the console output looked like it does now, except it would show say block `#10`, then a couple minutes later block `#23`.  Same looking log output as after the first restart, only after the restart it shows block `#10` then ~15 seconds later block `#11`.

**Comment by keorn** [comment]
@MicahZoltu Have you experienced the issue since or can we close the issue?

**Comment by arkpar** [comment]
Most probably fixed in 1.3.7
Please reopen if you still have that issue in 1.3.9

**Comment by MicahZoltu** [comment]
I have not attempted to delete/re-sync my blockchain since submitting this bug, so no, I have not run into it again.  The problem went away after first restart.  My concern is that users that don't do a restart after their initial sync will see odd behavior where they won't get blocks in a timely fashion.

I recommend against closing the issue unless others have explicitly tried doing a clean install and watching the block fetching behavior after completing a full initial sync without restarting Parity on Windows.

**Comment by MicahZoltu** [comment]
@arkpar 

I feel like you aren't reading what I am saying.  This issue is a first-run issue.  Unless I regularly delete my entire blockchain I will *not* see the issue again.  That doesn't mean anything is fixed, it just means that I am not deleting my blockchain on a regular basis.  Closing this issue without verifying it is fixed is just sweeping the problem under the rug until the next person runs into it and they may not be as technically savvy or willing to submit an issue to GitHub.

I can totally appreciate putting this on the backburner as it isn't a critical failure, but I don't see any evidence that this has been fixed.
