### ISSUE TITLE
Cannot add wallet contract

### ISSUE THREAD

**Issue by githubacc32** [ethcore/parity#2533]
Hello,
when trying to sign the added wallet contract with the "Parity Trusted Signer", I get this error:

Transaction cost exceeds current gas limit. Limit: 1648649, got: 3000000. Try decreasing supplied gas.

What can I do about it?
Thanks!

**Comment by keorn** [comment]
Try decreasing supplied gas? The block gas limit is at 1648649 and you supply more than that.

**Comment by githubacc32** [comment]
I'm sorry, I don't quite understand it.
How would I do that (inside the parity web UI)?
Thanks.

**Comment by tomusdrw** [comment]
When transaction is created it can supply Gas Limit or rely on default. In current network conditions gas limit is trimmed down so deployments with hardcoded gas limits are broken.
It should work fine after EIP158 is in, otherwise most probably it's not really possible to deploy contract with such high gas requirement.
