### ISSUE TITLE
Huge incoming traffic

### ISSUE THREAD

**Issue by anton44eg** [ethcore/parity#2552]
After 1.3.4 update my node use 5x-10x more incoming traffic. 
Proof http://prntscr.com/cruvi5

**Comment by Atrides** [comment]
I confirm this issue. But I cannot exactly determine why some nodes (non-public) have much more incoming traffic then other.

**Comment by Atrides** [comment]
Update: all parity-nodes with 1.3.5 version have HUGE incoming traffic from geth <=1.4.15
with geth 1.4.16 no problem

**Comment by tomusdrw** [comment]
1.3.4 increased incoming traffic was caused by:
1. Increase of default transaction queue size in Parity (1024->2048)
2. Heavy transactions spam attack that forced us to release 1.3.5 right after that.
Currently it should be back to normal (maybe a bit higher then couple of weeks ago because of low block gas limit causing more transactions to be pending in the queue)

Please re-open if it's still a case in 1.3.8 version of Parity.
