### ISSUE TITLE
Notify users when transaction arrives for any of their accounts

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2556]

**Comment by ngotchac** [comment]
Got this to work thanks to the Trace API (thus needs to be enabled), since you can make a request for transactions on several addresses (not available on Etherescan API...)
I'm not sure how would that be possible without tracing enabled then, because making a request for each account to Etherescan at each block sounds like a big overhead... Any thoughts? Maybe we should have some servers running Parity with tracing enabled... ?

**Comment by tomusdrw** [comment]
What about this: https://etherscan.io/apis#websocket

**Comment by ngotchac** [comment]
Thought about this, I guess it would work. Only thing is that, for example for the list of transactions, there's a footer expliciting that Etherscan is used to get those, and here it won't. Is that an issue ?
Will try to implement it though.

**Comment by rphmeier** [comment]
it seems a bit hacky to rely on etherscan for data which should be available from the connected parity node (pub/sub support would be nice here :) )

**Comment by jacogr** [comment]
I think the correct solution would be -

1. short-term, poll for our accounts when new block arrives (which is also currently polling, but at least abstracted away until we have proper pub-sub)
2. medium-term use node pub-sub to provide this info same

I don't think we should rely on 3rd parties more than we already do.

**Comment by ngotchac** [comment]
@jacogr How would we poll transactions for any account without using Etherscan anyway ?
