### ISSUE TITLE
On first load of the UI, content images show up empty

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#2651]
e.g. GAVcoin image on main page. Reload fixes. Only for the very first load has these issues? Maybe related to dev mode?

**Comment by tomusdrw** [comment]
API returns `503` if node is still syncing (I think it is assumed default right after starting parity)

**Comment by jacogr** [comment]
In this case however it seems to be the first time a UI is connected to the running node. So it really could be Webpack releated... I pops up each time the first time `npm start` is run, this morning my node has actually been up since last night and fully synced.

**Comment by derhuerst** [comment]
From time to time, I get "node is syncing", even tough my node has been running for at least an hour.

**Comment by keorn** [comment]
https://github.com/ethcore/parity/pull/2699 should fix that.

**Comment by ngotchac** [comment]
The issue is that, right after starting Parity, if requested `http://localhost:3000/api/content/d40679a3a234d8421c678d64f4df3308859e8ad07ac95ce4a228aceb96955287/`, to HTTP response is a 302 redirect to `http://localhost:3000/d40679a3a234d8421c678d64f4df3308859e8ad07ac95ce4a228aceb96955287/`. It should whether be a 302 to the same address, or just return the fetched file if available.
This is a Core issue from what I can tell.
