### ISSUE TITLE
Missing header in dapp: "X-Frame-Options"

### ISSUE THREAD

**Issue by sebs** [ethcore/parity#2679]
"X-Frame-Options header is not included in the HTTP response to protect against 'ClickJacking' attacks."

> Most modern Web browsers support the X-Frame-Options HTTP header. Ensure it's set on all web pages returned by your site (if you expect the page to be framed only by pages on your server (e.g. it's part of a FRAMESET) then you'll want to use SAMEORIGIN, otherwise if you never expect the page to be framed, you should use DENY. ALLOW-FROM allows specific websites to frame the web page in supported web browsers).

This affects

* /
* /contracts
* /deploy-contract
* /home
* /home/
* /send

**Comment by tomusdrw** [comment]
`X-Frame-Options` is not present only on the `/home` page - because previously it was used as Cross-Origin Local Storage, but clickjacking on a home page cannot lead to any security breach afaict.

All other pages (`http://localhost:8080/wallet` and `http://wallet.parity`) are including the header.

Note that going to`http://localhost:8080/send` will redirect you to the home page (not to the wallet as you may expect).

We are re-designing the UI in `master` anyway, so those dapps will be removed shortly.

**Comment by sebs** [comment]
"Cross-Origin Local Storage" for what? Keys?

**Comment by tomusdrw** [comment]
It was used for account names, but will be removed in upcoming version and `X-Frame-Options` header will be included everywhere.

**Comment by sebs** [comment]
![h5](https://media.giphy.com/media/3oz8xrUuz2KtWlbyHm/giphy.gif)
