### ISSUE TITLE
Edit metadata does not work

### ISSUE THREAD

**Issue by debris** [ethcore/parity#2968]
<img width="769" alt="screen shot 2016-10-29 at 16 32 50" src="https://cloud.githubusercontent.com/assets/2613714/19830315/85600288-9df5-11e6-81f2-7187a85dbcaa.png">

After I pressed `Save`, nothing happened.

Latest master

**Comment by jacogr** [comment]
Ok, know what happens here - the change detection is only done when you leave the field, I'm guessing the save didn't trigger the "leave" soon enough. It has been on the todos to make this more robuset, will prepare a fix one way or another.

**Comment by jacogr** [comment]
Scratch the above. Not the issue. Not sure why it didn't work, cannot replicate it here at all. (On master.)

**Comment by jacogr** [comment]
Replicated on my master build. (Not via development environment through, but definitely an issue somewhere)

**Comment by jacogr** [comment]
@debris When you build master again, could you just check if you still see this. 

I have been able to initially verify and since then my builds yesterday and today from latest master has not shown the issue. So it either got fixed along the way, was a pre-compiled glitch or intermittent. (Latter would obviously be a bit of a nightmare)

**Comment by debris** [comment]
it works now 👍
