### ISSUE TITLE
Cannot compile valid contract, no error message

### ISSUE THREAD

**Issue by MaxBinnewies** [ethcore/parity#3041]
Hello,

I am trying to deploy the following contract through the Ethereum Wallet that comes with Parity:
`pragma solidity ^0.4.2;

contract DateUtility {
   function dateIsInvalid(uint time) public returns(bool retInt) {
        uint dateNow = now;
        if (time > dateNow) {
            return false;
        } else {
            return true;
        }
    }    
}`

It says "Error: Error while compiling code.", nothing else. I have tried various solidity-versions in the first line, but no success. With this little information I have no idea what the problem is. The exact same code compiles in the online compiler, the compiler for VS Code and on Ethersim. 
When I run parity in geth mode and try to deploy it through the regular Ethereum Wallet, it apparently compiles it, but when I try to deploy it, it tells me "It seems this transaction will fail. If you submit it, it may consume all the gas you send". When I try to send it anyways, it just says "Invalid params" and aborts. Without a proper error message I have no idea where to even look for the problem...

I am using Parity/v1.3.9-beta-e9987c4-20161021/x86_64-windows-msvc/rustc1.12.0 and have an account with more than 1 Ether hooked up to Parity. Do you guys have idea whats going on or how I could find out what the problem is?

Thank you,
Max

**Comment by tomusdrw** [comment]
It seems that there two separate problems here:
1. Compilation of contracts with Parity
2. Deploying contract with builtin Ethereum Wallet.

Ad. 1 - Parity is using compiler available in your system. So make sure that `solc.exe` is available as a command in `cmd` (should be installed and added to the `PATH`)

Ad. 2 - Deploying a contract may fail with builtin Ethereum Wallet, the Wallet is sending uncorrectly formatted data to Parity RPC. Since we have deprecated builtin Wallet, and 1.4.x series will come with new UI I would recommend to either switch to 1.4 when released or use external Mist/EthereumWallet with `parity --geth`.

Running with `lrpc=trace` may also help with debugging.
