### ISSUE TITLE
signer new-token stopped working

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#3087]
Latest master -

```
$ parity signer new-token
$
```

No output at all.

**Comment by gavofyork** [comment]
fwiw i'd prefer to get rid of this altogether and just make `parity ui` pass the token directly.

**Comment by tomusdrw** [comment]
Is still useful to authorize non-ui Signer or second browser (you could copy&paste the link instead though).

Also `parity ui` should generate token only once and then return the same all the time otherwise we need some kind of cleanup for tokens that are no longer used (or were not used at least once)

**Comment by gavofyork** [comment]
>Is still useful

Shouldn't ever be needed - any trusted UI should be able to generate a new token for any secondary trusted interfaces.

**Comment by tomusdrw** [comment]
Sure, so should CLI Signer interface.
