### ISSUE TITLE
RPC API should return transaction "v", "r", "s" values

### ISSUE THREAD

**Issue by fjl** [ethcore/parity#3158]
Please return these values because they make reconstructing complete transactions possible on the client side. Geth will start returning these in v1.5.

**Comment by stevenroose** [comment]
Version `Parity//v1.4.3-beta-08a4220-20161114/x86_64-linux-gnu/rustc1.13.0` (current latest Docker beta-release), which should include #3172 does still make `ethclient` throw an `missing required JSON transaction signature fields` error:
https://github.com/ethereum/go-ethereum/blob/b10bcd924ba79f9faa5b8f2d273a7ee02d7b89f5/core/types/transaction.go#L196

So this issue is somehow not yet resolved.

**Comment by tomusdrw** [comment]
My bad, seems that I forgot to mark the PR to be backported to beta branch. Made additional PR now.

**Comment by stevenroose** [comment]
Thanks!

**Comment by tjayrush** [comment]
I summarized seven differences between 'geth' and Parity and the documentation in this issue: https://github.com/ethcore/parity/issues/3601. I did tests against about 1,000 randomly selected blocks and found only the noted differences.
