### ISSUE TITLE
How to generate new token on windows?

### ISSUE THREAD

**Issue by keuge** [ethcore/parity#3257]
So how?
![fsdf](https://cloud.githubusercontent.com/assets/7301484/20098486/2231384e-a5c5-11e6-9f0a-f27ffce57156.png)

**Comment by rphmeier** [comment]
Just as the hint says: run `parity signer new-token` and copy the produced token into the box below. This is used to authenticate your signer with parity.

**Comment by russdirks** [comment]
The phrase "run `parity signer new-token` and supply the token below" was a bit confusing to me.  I read it as "take the token below and supply it as input to the `parity signer new-token` command", which had me stumped, because the field is blank.

A wording that would make more sense to me, at least, would be "run `parity signer new-token`, and paste the generated token into the space below"
