### ISSUE TITLE
Name registry feature in Parity 1.4.0

### ISSUE THREAD

**Issue by keuge** [ethcore/parity#3284]
Is this Name registering feature with in Parity registering Unique names for wallets for 1 eth? So if i register my name it will be permanetly for me to use and noone can register it? And how to use this registered name?

**Comment by jacogr** [comment]
Currently we use it extensively to name our contracts. When you register a name, it indeed gets assigned to you. We have something on our list of issues where you will be able to search the Registry for names to send to, i.e. I will be able to tell you to send it to "jacogr" and it will look up the address.

For now, very useful for dapps since they can register their names of Morden/Homestead and always find their associated contracts, shortly it will be quite useful for normal accounts as well.
