### ISSUE TITLE
Account opened with --password is unable to unlock

### ISSUE THREAD

**Issue by rilakstitch** [ethcore/parity#3334]
I have generated an account with --password {PASSFILE} which {PASSFILE} is a text file containning a cleartext password. The command finished without asking me a password and given me an address.

Now I want to send fund using Dapp with that address and type in the password contained in {PASSFILE} but the authentication is wrong. 

I am not sure if I have misunderstanded something or else?

**Comment by tomusdrw** [comment]
What exact command did you use to generate the account? Can you make sure that the account is in control of your node by running `$ parity account list`?

**Comment by rilakstitch** [comment]
Thanks for the quick response!

I used this command to generate the account
parity.exe --password "FILE.txt" account new

And the account is shown when running $ parity account list and also controllable using Dapps.

**Comment by tomusdrw** [comment]
Ok so the problem seems to be that the password for you account is the whole file content, while when unlocking account we expect one password per line. Probably there were some additional whitespace characters in your password file causing this problem now.

If you need to get this account back:
1. Please copy the file you used initialy and keep it safe (don't open it with any editors! / mark as readonly)
2. Try compiling and running `ethstore` tool: https://github.com/ethcore/parity/wiki/Setup#building-from-source and use `change-password` feature from there.
3. Get in touch with me on Gitter for direct help: https://gitter.im/ethcore/parity

**Comment by rilakstitch** [comment]
Thank you, I'll try to use ethstore to see if I could get back the account!
BTW, I am sure the file have NO whitespace, just a single password there.

I'll post here for any update.

**Comment by rilakstitch** [comment]
Thanks @tomusdrw !
Finally I have successfully changed the password using ethstore and got back the fund (~130 ETC!) in the account!
