### ISSUE TITLE
Enhance UI dappInterface detection when proxy is present

### ISSUE THREAD

**Issue by jacogr** [ethcore/parity#3337]
From https://github.com/ethcore/parity/pull/3311

- it may return 0.0.0.0 in such case we should fallback to window.location.hostname
- if window.location.hostname == 'home.parity' we should fallback to proxy address instead of using dappsInterface

**Comment by tomusdrw** [comment]
Actually to cover all setups it might be best to follow this rules:
1. `if window.location.hostname=='home.parity' then try http://dapps.parity:<dappsPort>`
2. `try http://${window.location.hostname}:<dappsPort>`
3. `try http://<dappsInterface>:<dappsPort>`

**Comment by jacogr** [comment]
"try" is the difficult part here - we set and then just load resources. So when we set, we need to be 99.9% confident we have it right. (We only have limited places where we actually interact with the hosts via things like `fetch`, mostly it is via stock-standard HTML, e.g. `img` tags)

**Comment by tomusdrw** [comment]
Updated my comment, (`try->use` in some cases).
We can skip (2) then, but we won't cover cases like:

`$ parity --dapps-interface 192.168.0.10 --signer-interface 192.168.0.10 --dapps-hosts <externalip> --signer-no-validation`

`Parity (192.168.0.10) -> Router/ReverseProxy (<externalIp>) <- Client (Browser)`

But since `--signer-no-validation` is not recommended anyway we can move it to separate issue.

**Comment by jacogr** [comment]
Currently we do -

1. Not handled (first thing to address)
2. We do this everywhere now
3. Not yet...

The initial idea I had was to cater for 1 (special case), 3 do this everywhere, 2 as fallback where 0.0.0.0 or something similar. Need some thought.
