### ISSUE TITLE
decimal for erc20-esque transfer method

### ISSUE THREAD

**Issue by subtly** [ethcore/parity#3389]
We noticed with golem (0xa74476443119A942dE498590Fe1f2454d7D4aC0d) that the decimal isn't considering, so transferring 1 token only sends 1/1000000000000000000 GNT. This is for the 'transfer' method.

It would be helpful if, when adding a contract, parity looks for 'decimal' field and then has a checkbox (checked by default) which flags the token as having decimal – when rendering balance, or, when accepting input for a solidity-abi argument that looks like _?(value|val|amount).

This sounds kind of messy, but I suppose with solidity and erc20 there's still a lot of ambiguity for binding UX interactions like this. Accordingly, such logic would ideally be tied to the solidity version encoded in the bytecode.

Note: As GNT isn't intended for human consumption, it doesn't implement everything specified in ERC20. However, it does specify the metadata properties (decimal, name, symbol, etc.).

**Comment by gavofyork** [comment]
tokenreg provides a means for ensuring the token's decimal point is in the right position, and i'm of the opinion that a registry is the best place for metadata, rather than with the underlying token-control logic itself.

**Comment by jacogr** [comment]
If the transfer is done via the "Transfer" mechanism under Accounts, the decimals should be added to the right place since it uses TokenReg in the background which has been registered with the correct decimals for Golum. So `1.0` there will transfer 1000000000000000000. (Same with all other tokens)

The contract tab is really for technical users, so the assumption is that they know what to do and no translation of the parameters are done. (It is a dumb interface - only reads the methods and allows technical users to supply the values based on their understanding of the contract)

I think internally we are all subscribing to the vision that normal users whould no enable or use the contract tab. At least for tokens and the registry, there is no reason for them to do so since they should be able to view balances and do transfers in the normal interface.
