### ISSUE TITLE
Update ABI decoder with Solidity 0.4's new ABI definition format

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#3392]
Solidity 0.4 has a broken design in that the ABI definition it outputs includes an additional `fallback` entry if you implement the fallback function. (It's broken because the fallback function is an extra-ABI mechanism - the ABI shouldn't know nor care about the notion of a fallback - it's too low-level.)

If found, this portion of the ABI definition should be either ignored or used in some way as it makes sense.

Released to this is the additional `payable` field in ABI method definitions. This may also be used.

**Comment by jacogr** [comment]
We do cater for both these already (we had to bring it in since some of our contracts are compiled with 0.4.1). Fallback is basically the old `function() {}` (I'll just double-check what we don on the UI here - want to allow calls to the default functions, but as you rightly said, need to be careful with stuff that people's should have to care about)

Payable however we do parse, but actually we should use it in the "execute contract" modal as well. If present allow to send ETH, otherwise don't. (Only for 0.4+ ABIs)

**Comment by gavofyork** [comment]
![image](https://cloud.githubusercontent.com/assets/138296/20239175/9ee12b96-a8fa-11e6-995f-eca3d9cf61ab.png)

Note the error on the "fallback" function.
