### ISSUE TITLE
web3 getTransactionReceipt does not give back blockHash nor blockNumber

### ISSUE THREAD

**Issue by wighawag** [ethcore/parity#3569]
I was using getTransactionReceipt (https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgettransactionreceipt) and relied on the receipt.blockNumber

Since I switched to remove the --geth option in parity, I still get the receipt when the tx is mined but it does not contains the blockHash nor the blockNumber

**Comment by tomusdrw** [comment]
`blockNumber` is not null only for non-pending transactions, so you should poll for the receipt until the `blockNumber` is there.

**Comment by wighawag** [comment]
I thought the receipt existed only when the tx was mined 

That's what the doc says  :

```
Note That the receipt is not available for pending transactions.
```

Also note that this issue is not present when using ```--geth```

**Comment by gavofyork** [comment]
this is desired behaviour - see the wiki for the RPC specs that parity implements. if you prefer to work with the geth bug, then use `--geth`.

as a side note: historically, cpp-ethereum implemented this RPC like parity (and that predated the docs you quote). this is because it gives more information to the user, since you are able to see ahead of time which logs and gas usage the transaction had. geth apparently did it differently. geth's simpler behaviour made its way into the ethereum-foundation-hosted docs that you quote for no good reason.

**Comment by wighawag** [comment]
ok, this is a bug in geth then and the web3 doc.  I expected the ethereum-foundation-hosted docs to be in agreement with the spec. Thanks for clarifying.
I understand that it is not your responsibility, but is there any doc on all the discrepancy between geth and parity ?

**Comment by wighawag** [comment]
According to https://github.com/ethereum/go-ethereum/issues/3323 getTransactionReceipt should return null for pending tx since ligth client will have to report null and we want a unified api.

For my use case I solved my issue by checking both null and receipt.blockNumber but it would be good if different implementation agree on what to return. 

Thanks

**Comment by tomusdrw** [comment]
So it's still an extra piece of information you can get from the RPC. Depending on the transaction queue settings two nodes may or may not return the pending receipt for the same transaction (since one node can execute it and the other one don't).

Pending receipt is easily distinguishable from in-chain receipt and it's consistent with other APIs (`eth_getBalance,eth_getCode,eth_getTransactionCount,eth_getStorageAt,eth_call,eth_getBlockByNumber,eth_getTransactionByBlockNumberAndIndex,eth_newFilter,eth_getFilterLogs`) It seems that `getTransactionReceipt` is actually an exception where `pending` state is not available.

If you are not running Parity with `--force-sealing` and you're not mining you will never receive pending receipts for non-local transactions (same for light clients).

**Comment by wighawag** [comment]
OK, make sense. Thanks for taking the time to clarify
