### ISSUE TITLE
 URLs as `--usd-per-eth` are not accepted

### ISSUE THREAD

**Issue by tomusdrw** [ethcore/parity#4201]
The [documentation here](https://github.com/ethcore/parity/blob/7cab6ac2631f4b8e6f69ef2aa36fc4f4b1b32edb/parity/cli/usage.txt#L221) states that `--usd-per-eth` can be a web service, but URLs are not accepted.

`price_info` should support customizing the URL

**Comment by rphmeier** [comment]
Agreed, but we should settle on a standard format for price to be returned by custom web services. Could be a `JSON` document or just a dec/hex-encoded number.

**Comment by gavofyork** [comment]
they were never actually meant to be accepted (there's no standard format as @rphmeier says, so this couldn't work); the idea was that names of them could be and the decoding logic would be included our side. so far i only did one (partly because i could only find one service).

closing since URLs themselves won't work alone. i'd say the enhancement is tenuous at best; we should probably just be aiming to add another couple of service providers (and their decoding logic) to the list.
