### ISSUE TITLE
Multisig wallet contract doesn't throw when sub-call throws.

### ISSUE THREAD

**Issue by Mindgameproject** [ethcore/parity#4304]
Why i cant send ICN from my contract? Its says out of gas
Parity 1.5.0

**Comment by gavofyork** [comment]
the easiest workaround is to use "advanced sending options" in the transfer dialog and then for "gas" enter 100000.

`eth_estimateGas` doesn't play well with current multisig wallet since it relies on the multisig's sub-call's OOG to propagate to the top.

that will need to be addressed in a new wallet contract.
