### ISSUE TITLE
No documentation for killing a daemon

### ISSUE THREAD

**Issue by superphly** [ethcore/parity#4517]
I've looked all over the documentation and can't for the life of me find anything that shows how to kill parity running in daemon mode.

**Comment by gavofyork** [comment]
`killall parity`?

**Comment by rphmeier** [comment]
Or perhaps find the pid with a `ps -e | grep parity` and then a `kill <pid>` (or even `kill -9 <pid>` if that fails to work)

**Comment by arkpar** [comment]
On linux you just kill a process. 
On Mac we'll be adding a UI to control Parity running in 1.6

**Comment by superphly** [comment]
the killall and kill -9 stuff wouldn't work because it's being started by the launchctl daemon stuff on MacOS. I'd be glad to contribute some docs for this and how to start/stop and remove the daemon...

**Comment by arkpar** [comment]
For 1.5 we have instructions shown in the installer. The source is here:
https://github.com/ethcore/parity/blob/beta/mac/install-readme.txt
This has been removed from the master codebase because the latest installer on Mac uses a different auto start mechanism and user now has an option to disable it through the standard Login Items UI or the Parity icon in the top bar.

**Comment by davidhq** [comment]
Even `launchctl stop io.parity.ethereum` as described in link above doesn't stop the daemon (it gets restarted right away).

**Comment by 5chdn** [comment]
@davidhq does this do the trick:

    $ launchctl unload /Users/$USER/Library/LaunchAgents/io.parity.ethereum.plist

This will prevent restarting the daemon after stopping it.

**Comment by davidhq** [comment]
@5chdn yes, thank you
