### ISSUE TITLE
Contract calls don't return values sent with contract executions in DevelopmentChain mode (Parity 1.5.2)

### ISSUE THREAD

**Issue by vbaranov** [ethcore/parity#4527]
```
./parity --chain chain.json ui
```

where chain.json is from [default configuration](https://github.com/ethcore/parity/wiki/Private-development-chain)

Contract:
```
pragma solidity ^0.4.9;

contract Test {
    event Ev(string key);
    
    mapping(string => string) mapp;

    function setMapping(string key, string val) {
        mapp[key] = val;
        Ev(key);
    }
    
    function getMappingVal(string key) constant returns(string) {
        return mapp[key];
    }

}
```

`setMapping` tx is immediately mined every time.
But events aren't sent sometimes. And `getMappingVal` returns an empty string at the same time.
The same contract works fine for every tx, for example, with Ropsten chain (--testnet).

See it in [action](https://drive.google.com/file/d/0B-OyzbGTsafnY0V2VGxpVkZWZEU/view)

**Comment by ngotchac** [comment]
Hi, I just have two comments:

1. The given Solidity code seems wrong, at least the `getMappingVal` method : `return mapp[key];` instead of `return mapp[key].val;`
2. In the example you linked, you are sending `0.01 ETH` with the transaction. However since Solidity v0.3.<something> (I think), you must add `payable` to the method definition for it to receive any ETH.

So are you sure it's not just the comment 2 that prevented your transaction to succeed?

**Comment by vbaranov** [comment]
Hi, thanks for comments.
1. Yes, you are right. I've updated Solidity code to that I really used. 
2. I'll check you suggestion and let you know the result.

**Comment by ngotchac** [comment]
Great, thanks !

**Comment by vbaranov** [comment]
The issue is not reproduced with Parity 1.5.4.

**Comment by ngotchac** [comment]
Great news, thanks for letting us know
