### ISSUE TITLE
Syncs stalled on Ropsten, forced to delete chaindata and restart

### ISSUE THREAD

**Issue by wojo** [ethcore/parity#4879]
Started a full syncs with both geth and two parity instances last night late (around midnight). Woke up to both the parity instances frozen at certain blocks around 1:10-1:20 AM EST (see [logs.txt](https://github.com/ethcore/parity/files/836610/logs.txt)), geth finished just fine albeit slower through the entire process.

Last night was also a change for DST at 2am (also in [logs.txt](https://github.com/ethcore/parity/files/836610/logs.txt) attached), and I don't think this could be the issue but perhaps?

Included `-l sync=trace` retry for one of the instances to aid debugging these stalls.

**Comment by 5chdn** [comment]
Ropsten is pretty much dead due to attacks in Februrary. You can read more details here: http://ethereum.stackexchange.com/q/12477/87

For now, if you need a public testnet, you can use Kovan with `parity --chain kovan` (this requires Parity 1.5.5 or later. You can read more on Kovan config here: https://github.com/kovan-testnet/config
