### ISSUE TITLE
Intro screen requiring new account upon every restart if all current accounts are in a Vault

### ISSUE THREAD

**Issue by xenoexclusive** [ethcore/parity#4894]
Upon upgrading to 1.6.2, after putting accounts into vault, every time I load up Parity I need to create a new account just to get past the parity intro screen.

**Comment by 5chdn** [comment]
Just tested, can reproduce.

**Comment by jacogr** [comment]
Yes, would be an issue & oversight. Since the UI pops up the account creation when no accounts are found (and it doesn't have any access to vault accounts until the vault has been opened).

As a work-around, keep a single account out of the vaults, will need to see what we can do logic wise, maybe "no accounts" & "no vaults" as a determination instead of just "no accounts".
