### ISSUE TITLE
JSONRPC should be able to handle a large number of connections

### ISSUE THREAD

**Issue by gavofyork** [ethcore/parity#799]

**Comment by gavofyork** [comment]
running ethminer and netstats on the same machine causes the netstats entry to hang.

**Comment by jacogr** [comment]
Thanks for this one - I have been putting together a wallet that connects to your local instance. It started as a "I want to play with Parity RPC" and ended with a "make it quite fully featured since I cannot Mist on my machines". (project in question http://theblock.github.io/)

One thing I have noticed is that Parity RPC is fast, but it definitely doesn't handle the same number of connections as Geth. On startup there is a noticeable Parity delay on RPC when throwing multiple connections at it.

PS: I have seen some RPC issues (i.e. where things break in Parity, but work in Geth), will track them down and log separately if still issues with the latest versions.

**Comment by General-Beck** [comment]
a lot of connection errors from a miner.
Most importantly - submit failed hashrate
https://slack-files.com/T0CR0AD70-F0XCJMTMY-268193adac

**Comment by arkpar** [comment]
#901
